
#### general settings

name: I_IRN_DB_x4_scratch_DIV2K
use_tb_logger: true
model: I_IRN
distortion: sr
scale: 4
gpu_ids: [0]


#### datasets

datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: datasets/train/train2014 # path to training HR images
    dataroot_LQ: ~ # path to training reference LR images, not necessary, if not provided, LR images will be generated in dataloader

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 144
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: datasets/train/DIV2K_train_HR # path to validation HR images
    dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader


#### network structures

network_G:
  which_model_G:
      subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [8, 8]
  scale: 4
  init: xavier


#### path

path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~


#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 1e-4
  beta1: 0.9
  beta2: 0.999
  niter: 250000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [30000, 60000, 90000, 150000, 180000, 210000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l1

  manual_seed: 10

  val_freq: !!float 5e3
  #  val_freq: 100
  lambda_fit_forw: 64.
  lambda_rec_back: 1.
  lambda_center: 0
  weight_decay_G: !!float 1e-12
  gradient_clipping: 10

#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
